### ISSUE TITLE
git 컨벤션

### ISSUE THREAD

**Issue by JaeminKang** [WinterSpringProject/PROJECT-PIND#1]
# git 컨벤션

- 커밋 메시지는 제목, 공백 한 줄, 본문로 구성한다.
- 제목은 동사원형으로 시작하며, 영어로 작성한다.
- 본문은 반드시 한글로 작성하며 '무엇을', '왜'의 관점에서 작성한다.
- 제목에는 반드시 #(번호)로 이슈번호가 표시되어야 한다.

**Comment by khcho902** [comment]
commit 컨벤션의 경우 [좋은 git 커밋 메시지를 작성하기 위한 8가지 약속](https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/)에 나와있는 내용은 기본적으로 모두 따라가는게 좋을거 같다고 생각합니다. 
```
1. 제목과 본문을 한 줄 띄워 분리하기
2. 제목은 영문 기준 50자 이내로
3. 제목 첫글자를 대문자로
4. 제목 끝에 . 금지
5. 제목은 명령조로
6. Github - 제목(이나 본문)에 이슈 번호 붙이기
7. 본문은 영문 기준 72자마다 줄 바꾸기
8. 본문은 어떻게보다 무엇을, 왜에 맞춰 작성하기(한글로!!!!)
```
본문은 재민님 의견처럼 반드시 한글로 작성하는거 찬성입니다 ㅎㅎ 그리고 본문이 굳이 필요없을 경우에는 작성하지 않아도 될거같습니다. 

추가적으로 [udacity style guide](https://udacity.github.io/git-styleguide/) 방식으로 커밋 제목을 작성하고 재민님 의견처럼 이슈번호를 추가면 좋을거 같습니다. 
```
type : #이슈번호 Subject(제목) 

type 종류
 - FEAT        : 새로운 기능 추가 
 - FIX         : 버그 수정 
 - DOCS        : 문서 수정 (ex, README.md)
 - STYLE       : 포매팅, 세미콜론 누락 등 수정 (기능상 코드변경 없음)
 - REFACTOR    : 기존코드 리팩토링
 - TEST        : 테스트 코드 작성 (기능상 코드변경 없음)
 - CHORE       : 빌드 업무 수정, 패키지 매니저 수정 (기능상 코드변경 없음)
```

**Comment by JaeminKang** [comment]
말씀하신 것 반영하여 위키에 정리하겠습니다.
