### ISSUE TITLE
클라우드 배포

### ISSUE THREAD

**Issue by JaeminKang** [WinterSpringProject/PROJECT-PIND#23]
프론트엔드 팀에게 API를 제공할 수 있도록 미리 클라우드 배포 준비를 시작하고자 합니다.

* EC2 서비스 배포

* 파일 저장
(1) 장기간 지속 파일 :  컨테이너 내 저장
(2) 단기간 지속 파일 : S3 저장 (수명주기를 설정해 짧은 기간 파일 유지)
:  Amazon S3 스토리지(S3 Standard 스토리지 클래스) 프리티어의 경우 매달 5GB, 20,000건의 GET 요청, 2,000건의 PUT, COPY, POST 또는 LIST 요청, 15GB의 데이터 송신 가능

Endpoint = 52.78.169.232:8080

Reference
https://jojoldu.tistory.com/300
https://willseungh0.tistory.com/2

**Comment by Ohhong** [comment]
maria DB를 따로 ec2에 올려서 사용할 계획으로 알고있었는데 아니었을까요?

**Comment by JaeminKang** [comment]
> maria DB를 따로 ec2에 올려서 사용할 계획으로 알고있었는데 아니었을까요?

GLFP 팀은 ec2에 mariaDB를 올려서 사용할 계획이라고 들었는데, 저희는 RDS를 활용할 계획입니다.

**Comment by Ohhong** [comment]
아하 혹시 RDS를 사용하기로 한 이유가 있을까요?
직접 DB 구축 및 관리 작업을 해보시는 것도 좋을것 같은데요

**Comment by JaeminKang** [comment]
> 아하 혹시 RDS를 사용하기로 한 이유가 있을까요?
> 직접 DB 구축 및 관리 작업을 해보시는 것도 좋을것 같은데요

그럼 저희도 EC2에 DB 구축해보겠습니다~~

**Comment by Ohhong** [comment]
아하 그래보면 좋을 것 같아요~
굳이 ec2 가 아니라 전에 말씀드렸듯이 azure, GCP에도 무료로 사용가능하니
여러 개의 vm을 띄워보시는것도 좋아보여요
