### ISSUE TITLE
JPA JPQL Query 사용 시 DTO 매핑 방법

### ISSUE THREAD

**Issue by JaeminKang** [WinterSpringProject/PROJECT-PIND#26]
어떤 방법을 통해 매핑하는 것이 최선일지 고민해봅시당.

Reference
https://www.popit.kr/jpa-native-query-사용-시-dto로-매핑하기/
https://vladmihalcea.com/jpa-query-map-result/
https://wky.kr/4

**Comment by khcho902** [comment]
올려주신 레퍼런스 잘보았습니다. 감사합니다 ~~~ QLRM를 사용하는 방식이 괜찮아보이네요. 해당 방법적용해보겠습니다!!!

**Comment by JaeminKang** [comment]
저희가 당면한 문제와 동일한 상황인 분의 질문글인데 크게 도움이 되진 않는군요 ㅠㅠ
https://stackoverflow.com/questions/48673742/hibernate-projection-jpql-query-to-dto-issue

**Comment by khcho902** [comment]
JPQL을 사용하는 상황에서 new 명령어를 사용하면 Object가 아닌 원하는 객체로 타입을 지정해줄수 있다고 합니다.  
new 명령어를 사용하기 위해서 아래와 같이 코드를 수정해보았습니다. 

- ProjectDTO에 생성자 추가 ( new 명령어를 사용하기 위해서는 적절한 생성자가 필요합니다.)
![image](https://user-images.githubusercontent.com/26676051/109042818-f5fcc700-7713-11eb-8503-50bcb2e6dae9.png)

- ProjectRepository (getProjectById 메소드의 반환타입을 ProjectDTO로 변경하고, select절에 new 명령어 추가)
![image](https://user-images.githubusercontent.com/26676051/109043618-dfa33b00-7714-11eb-8c2f-6f1a572a6e3e.png)

- 간단한 테스트
![image](https://user-images.githubusercontent.com/26676051/109043264-7e7b6780-7714-11eb-9f6c-254e42192e14.png)

테스트 해본결과  값은 제대로 조회가 되지만 아래와 같은 쿼리가 발생하는것을 볼 수 있습니다. 
(한번의 쿼리가 발생할것으로 예상하였지만, 총 4번의 쿼리가 발생하였고 N + 1 문제가 발생하는것을 확인할수 있었습니다.)
```
Hibernate: 
    select
        project0_.project_id as col_0_0_,       <--- 처음에 project_id, subject_id, region_id 만 조회되는게 문제인듯!!!!
        project0_.subject_id as col_1_0_,
        project0_.region_id as col_2_0_,
        count(participat3_.participate_id) as col_3_0_ 
    from
        project project0_ 
    left outer join
        subject subject1_ 
            on project0_.subject_id=subject1_.subject_id 
    left outer join
        region region2_ 
            on project0_.region_id=region2_.region_id 
    left outer join
        participate participat3_ 
            on (
                participat3_.project_id=project0_.project_id
            ) 
    where
        project0_.project_id=? 
    group by
        project0_.project_id
Hibernate: 
    select
        project0_.project_id as project_1_2_0_,
        project0_.mod_date as mod_date2_2_0_,
        project0_.reg_date as reg_date3_2_0_,
        project0_.description as descript4_2_0_,
        project0_.region_id as region_i7_2_0_,
        project0_.status as status5_2_0_,
        project0_.subject_id as subject_8_2_0_,
        project0_.title as title6_2_0_ 
    from
        project project0_ 
    where
        project0_.project_id=?
Hibernate: 
    select
        region0_.region_id as region_i1_3_0_,
        region0_.region_depth1 as region_d2_3_0_,
        region0_.region_depth2 as region_d3_3_0_,
        region0_.region_depth3 as region_d4_3_0_ 
    from
        region region0_ 
    where
        region0_.region_id=?
Hibernate: 
    select
        subject0_.subject_id as subject_1_4_0_,
        subject0_.subject_depth1 as subject_2_4_0_,
        subject0_.subject_depth2 as subject_3_4_0_ 
    from
        subject subject0_ 
    where
        subject0_.subject_id=?
```

@Query에 작성한 `new io.spring.pind.dto.ProjectDTO(p, s, r, count(pa))` 이부분에 있는 p, s, r 이 객체 그대로 넘어가는 방법을 찾는다면 깔끔하게 해결가능할거 같습니다. 
( p, s, r 이 아닌 모든 내부 값들을 나열해서 넘겨주면 가능하긴하지만 그러면 쿼리문이 너무 길어져서 보기가 안좋은거 같습니다)

**Comment by JaeminKang** [comment]
dto가 아닌 entity로 db 요청 결과를 받은 후, mapper를 통해 dto로 변환하는 방법은 어떻게 생각하시는지요?
https://huisam.tistory.com/entry/mapStruct

**Comment by khcho902** [comment]
일단 jpql을 사용하면 여러entity를 조회할경우 Object를 사용할수 밖에 없을거 같습니다. 
따라서 Querydsl과 같은 방법에 대해서도 학습하고 jpql대신 적용해보는것이 나을듯합니다.
(jpql 사용시 여러 entity를 조회해서 dto에 매핑하는 좋은 방법을 찾게되면 공유하도록 하겠습니다.)
