### ISSUE TITLE
README 작성

### ISSUE THREAD

**Issue by JaeminKang** [WinterSpringProject/PROJECT-PIND#3]
# README 작성

- 로고를 첨부할 것
- 기술 스택 기재할 것
- 프로젝트의 목적을 설명할 그림을 첨부할 것

**Comment by Ohhong** [comment]
잘 작성하셨습니다~ 몇 가지 보안할 점이 있긴합니다.
### 1. PR 관련
- 먼저 오른쪽 Linked pull request를 통해서 PR을 연결할 수 있고, PR이 머지될 때 자동으로 이슈도 같이 닫히니 좋을 것 같습니다.
- Ground Rule에 포함해주시면 좋을 것 같은데요. PR을 생성할 때 Reviewer에 저를 넣어주시고 적어도 n명 이상의 approve를 통해서 머지를 하는 것으로 규칙을 세우시는 게 좋습니다.
  - 아래 독스를 통해서 n명 이상의 approve가 없으면 merge를 block 시키는 가이드가 있으니 참고하시면 좋습니다.
  - https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule
- PR 내부의 Description도 작성해주시면 좋습니다.
- 마지막으로 main branch에서 머지하는 것 보다 issue#이라던지 특정 branch를 통해서 머지하는 것으로 통일하는게 어떨까요?
### 2. README.md 작성 관련
- 현재 image 디렉토리를 따로 만드셨는데 README.md 파일에 사용하는 것이라면 굳이 디렉토리를 만들지 않고 이미지 태그를 만들어서 사용할 수 있습니다.
  - https://worthpreading.tistory.com/83
- DS_Store는 맥에서만 생기는 특정 파일이기 때문에 .gitignore를 통해서 관리해주시면 좋습니다.
  - http://leechoong.com/posts/2018/ds_store/
  - https://nesoy.github.io/articles/2017-01/Git-Ignore

**Comment by JaeminKang** [comment]
![Uploading 스크린샷 2021-02-06 오후 12.02.55.png…]()

**Comment by JaeminKang** [comment]
<img width="189" alt="스크린샷 2021-01-28 오후 4 52 49" src="https://user-images.githubusercontent.com/19439884/107107658-de00f880-6875-11eb-9a9d-0ca48ee73f15.png">

**Comment by JaeminKang** [comment]
멘토님 조언에 따라 readme 페이지를 수정하였습니다.
