### ISSUE TITLE
프로젝트 이미지 관리 기능 추가

### ISSUE THREAD

**Issue by JaeminKang** [WinterSpringProject/PROJECT-PIND#37]
프로젝트 이미지 관리 기능을 추가하겠습니다.

1. 프로젝트 생성 시, 이미지 업로드 후 '프로젝트' 레코드 내 URL 등록
2. 프로젝트 삭제 시, 이미지 자동 삭제

* 기존 file controller의 기능과 중복되기 때문에 별도의 파일 업로드 및 삭제 객체를 생성해야 함.
* 프로젝트 생성 시, '이미지 첨부' 버튼을 누르면 uuid, path, name을 클라이언트에 반환하며 최종적으로 '등록하기' 버튼을 눌렀을 때 업로드 진행.

**Comment by gyumnnii** [comment]
저장소는 AWS S3를 사용하나요?

**Comment by JaeminKang** [comment]
> 저장소는 AWS S3를 사용하나요?

프로젝트 대표 썸네일은 내부에 저장하고, 고용량의 첨부파일은 S3로 관리할 계획입니다.

**Comment by gyumnnii** [comment]
> > 저장소는 AWS S3를 사용하나요?
> 
> 프로젝트 대표 썸네일은 내부에 저장하고, 고용량의 첨부파일은 S3로 관리할 계획입니다.

내부에 저장한다는 말은 서버쪽 디렉토리에 static하게 저장해두신다는 말씀이 맞을까요?

**Comment by khcho902** [comment]
일단 name, path, uuid를 갖고있는 image entity 생성하고,
이미지가 업로드 되어있다는 가정하에 project(entity)를 등록/삭제할때, image(entity)도 함께 등록/삭제되도록 구현해두겠습니다.
